sudo: required
language: go
go:
  - '1.7'
before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -q
  - sudo apt-get install glide -y
  - mkdir -p $GOPATH/bin
install:
  - glide install
script:
  - make test
before_deploy:
  - make cross-build
  - make dist
  - GOOS=linux GOARCH=amd64 make
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: 'dist/*.{tar.gz,zip}'
    on:
      tags: true
      go: '1.7'
  - provider: script
    skip_cleanup: true
    script: make ci-docker-release
    on:
      branch: master
      go: '1.7'
