sudo: required
services:
  - docker
language: go
go:
  - '1.9.3'
install:
  - make deps
script:
  - make test
before_deploy:
  - make cross-build
  - make dist
  - GOOS=linux GOARCH=amd64 make
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: 'dist/*.{tar.gz,zip}'
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: make ci-docker-release
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: DOCKER_IMAGE_TAG=$TRAVIS_TAG make ci-docker-release
    on:
      tags: true
      branch: master
